#include "frontend/font.h"

#include <cctype>
#include <unordered_map>

namespace gba::frontend {

namespace {

struct Glyph {
    char ch;
    // 7 rows of 5 characters each, top to bottom / left to right.
    // 'X' = pixel on, '.' = pixel off - written as ASCII art so each
    // glyph's shape can be checked by eye directly in this source file.
    const char* rows[kGlyphHeight];
};

// clang-format off
constexpr Glyph kGlyphs[] = {
    {'A', {".XXX.",
           "X...X",
           "X...X",
           "XXXXX",
           "X...X",
           "X...X",
           "X...X"}},
    {'B', {"XXXX.",
           "X...X",
           "X...X",
           "XXXX.",
           "X...X",
           "X...X",
           "XXXX."}},
    {'C', {".XXXX",
           "X....",
           "X....",
           "X....",
           "X....",
           "X....",
           ".XXXX"}},
    {'D', {"XXXX.",
           "X...X",
           "X...X",
           "X...X",
           "X...X",
           "X...X",
           "XXXX."}},
    {'E', {"XXXXX",
           "X....",
           "X....",
           "XXXX.",
           "X....",
           "X....",
           "XXXXX"}},
    {'F', {"XXXXX",
           "X....",
           "X....",
           "XXXX.",
           "X....",
           "X....",
           "X...."}},
    {'G', {".XXXX",
           "X....",
           "X....",
           "X.XXX",
           "X...X",
           "X...X",
           ".XXXX"}},
    {'H', {"X...X",
           "X...X",
           "X...X",
           "XXXXX",
           "X...X",
           "X...X",
           "X...X"}},
    {'I', {"XXXXX",
           "..X..",
           "..X..",
           "..X..",
           "..X..",
           "..X..",
           "XXXXX"}},
    {'J', {"..XXX",
           "...X.",
           "...X.",
           "...X.",
           "...X.",
           "X..X.",
           ".XX.."}},
    {'K', {"X...X",
           "X..X.",
           "X.X..",
           "XX...",
           "X.X..",
           "X..X.",
           "X...X"}},
    {'L', {"X....",
           "X....",
           "X....",
           "X....",
           "X....",
           "X....",
           "XXXXX"}},
    {'M', {"X...X",
           "XX.XX",
           "X.X.X",
           "X...X",
           "X...X",
           "X...X",
           "X...X"}},
    {'N', {"X...X",
           "XX..X",
           "X.X.X",
           "X.X.X",
           "X..XX",
           "X...X",
           "X...X"}},
    {'O', {".XXX.",
           "X...X",
           "X...X",
           "X...X",
           "X...X",
           "X...X",
           ".XXX."}},
    {'P', {"XXXX.",
           "X...X",
           "X...X",
           "XXXX.",
           "X....",
           "X....",
           "X...."}},
    {'Q', {".XXX.",
           "X...X",
           "X...X",
           "X...X",
           "X.X.X",
           "X..X.",
           ".XX.X"}},
    {'R', {"XXXX.",
           "X...X",
           "X...X",
           "XXXX.",
           "X.X..",
           "X..X.",
           "X...X"}},
    {'S', {".XXXX",
           "X....",
           "X....",
           ".XXX.",
           "....X",
           "....X",
           "XXXX."}},
    {'T', {"XXXXX",
           "..X..",
           "..X..",
           "..X..",
           "..X..",
           "..X..",
           "..X.."}},
    {'U', {"X...X",
           "X...X",
           "X...X",
           "X...X",
           "X...X",
           "X...X",
           ".XXX."}},
    {'V', {"X...X",
           "X...X",
           "X...X",
           "X...X",
           "X...X",
           ".X.X.",
           "..X.."}},
    {'W', {"X...X",
           "X...X",
           "X...X",
           "X.X.X",
           "X.X.X",
           "X.X.X",
           ".X.X."}},
    {'X', {"X...X",
           "X...X",
           ".X.X.",
           "..X..",
           ".X.X.",
           "X...X",
           "X...X"}},
    {'Y', {"X...X",
           "X...X",
           ".X.X.",
           "..X..",
           "..X..",
           "..X..",
           "..X.."}},
    {'Z', {"XXXXX",
           "....X",
           "...X.",
           "..X..",
           ".X...",
           "X....",
           "XXXXX"}},
    {'0', {".XXX.",
           "X...X",
           "X..XX",
           "X.X.X",
           "XX..X",
           "X...X",
           ".XXX."}},
    {'1', {"..X..",
           ".XX..",
           "..X..",
           "..X..",
           "..X..",
           "..X..",
           ".XXX."}},
    {'2', {".XXX.",
           "X...X",
           "....X",
           "...X.",
           "..X..",
           ".X...",
           "XXXXX"}},
    {'3', {".XXX.",
           "X...X",
           "....X",
           "..XX.",
           "....X",
           "X...X",
           ".XXX."}},
    {'4', {"...X.",
           "..XX.",
           ".X.X.",
           "X..X.",
           "XXXXX",
           "...X.",
           "...X."}},
    {'5', {"XXXXX",
           "X....",
           "X....",
           "XXXX.",
           "....X",
           "....X",
           "XXXX."}},
    {'6', {".XXX.",
           "X....",
           "X....",
           "XXXX.",
           "X...X",
           "X...X",
           ".XXX."}},
    {'7', {"XXXXX",
           "....X",
           "...X.",
           "..X..",
           ".X...",
           ".X...",
           ".X..."}},
    {'8', {".XXX.",
           "X...X",
           "X...X",
           ".XXX.",
           "X...X",
           "X...X",
           ".XXX."}},
    {'9', {".XXX.",
           "X...X",
           "X...X",
           ".XXXX",
           "....X",
           "....X",
           ".XXX."}},
    {'.', {".....",
           ".....",
           ".....",
           ".....",
           ".....",
           "..X..",
           "....."}},
    {',', {".....",
           ".....",
           ".....",
           ".....",
           "..X..",
           "..X..",
           ".X..."}},
    {'!', {"..X..",
           "..X..",
           "..X..",
           "..X..",
           "..X..",
           ".....",
           "..X.."}},
    {'\'', {"..X..",
            "..X..",
            ".....",
            ".....",
            ".....",
            ".....",
            "....."}},
    {'(', {"...X.",
           "..X..",
           ".X...",
           ".X...",
           ".X...",
           "..X..",
           "...X."}},
    {')', {".X...",
           "..X..",
           "...X.",
           "...X.",
           "...X.",
           "..X..",
           ".X..."}},
    {'-', {".....",
           ".....",
           ".....",
           "XXXXX",
           ".....",
           ".....",
           "....."}},
    {'_', {".....",
           ".....",
           ".....",
           ".....",
           ".....",
           ".....",
           "XXXXX"}},
    {':', {".....",
           "..X..",
           ".....",
           ".....",
           "..X..",
           ".....",
           "....."}},
    {'/', {"....X",
           "...X.",
           "...X.",
           "..X..",
           ".X...",
           ".X...",
           "X...."}},
};
// clang-format on

const std::unordered_map<char, const Glyph*>& GlyphTable() {
    static const std::unordered_map<char, const Glyph*> table = [] {
        std::unordered_map<char, const Glyph*> t;
        for (const Glyph& g : kGlyphs) {
            t[g.ch] = &g;
        }
        return t;
    }();
    return table;
}

} // namespace

int MeasureText(const std::string& text, int scale) {
    const int advance = (kGlyphWidth + 1) * scale;
    return static_cast<int>(text.size()) * advance - scale; // no trailing gap after the last glyph
}

int DrawText(SDL_Renderer* renderer, int x, int y, const std::string& text,
             int scale, SDL_Color color) {
    SDL_SetRenderDrawColor(renderer, color.r, color.g, color.b, color.a);

    const auto& table = GlyphTable();
    const int advance = (kGlyphWidth + 1) * scale;
    int cursorX = x;

    for (char rawCh : text) {
        const char ch = static_cast<char>(std::toupper(static_cast<unsigned char>(rawCh)));
        const auto it = table.find(ch);
        if (it != table.end()) {
            const Glyph& glyph = *it->second;
            for (int row = 0; row < kGlyphHeight; ++row) {
                for (int col = 0; col < kGlyphWidth; ++col) {
                    if (glyph.rows[row][col] != 'X') continue;
                    SDL_Rect block{cursorX + col * scale, y + row * scale, scale, scale};
                    SDL_RenderFillRect(renderer, &block);
                }
            }
        }
        // Unrecognized characters (lowercase already handled by toupper,
        // this covers anything truly outside the font) just advance the
        // cursor with nothing drawn - a blank cell, not a hard failure.
        cursorX += advance;
    }

    return cursorX - x - scale;
}

} // namespace gba::frontend
